# Copie este arquivo para .streamlit/secrets.toml e ajuste os valores abaixo.
GEMINI_API_KEY = "REPLACE_WITH_YOUR_KEY"
GENERATION_MODEL = "gemini-2.5-flash"
EMBEDDINGS_PROVIDER = "gemini"
TOP_K = 4
GEMINI_ENABLE_GOOGLE_SEARCH = true
# Caminhos obrigatórios para ingestão/indexação
DATASET_DOCS_DIR = "dataset/data/docs"
OUTPUT_DOCS_DIR = "project/data/docs"
INGESTION_MANIFEST_PATH = "project/data/ingestion_manifest.json"
